'use client';
import globalStyles from '../styles/reset.js';
//import { Inter } from 'next/font/google';

//const inter = Inter({ subsets: ['latin'] });

/*
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
*/

const RootLayout = ({ children }) => {
  return (
    <html lang='en'>
      <body>
        {children}
        <style
          jsx
          global
        >
          {globalStyles}
        </style>
      </body>
    </html>
  );
};

export default RootLayout;
